version: '3.8'
services:
  axonserver:
    image: axoniq/axonserver:4.5.9
    container_name: axonserver
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./events
        target: /eventdata
      - type: bind
        source: ./config
        target: /config
        read_only: true
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axonnet
  order-service:
    container_name: "order-service"
    build:
      context: ./order-service
    environment:
      - "AXONSERVER_HOST:axonserver"
      - "AXONSERVER_PORT:8124"
    ports:
      - "8080:8080"
    depends_on:
      - axonserver
    networks:
      - axonnet
  payment-service:
    container_name: "payment-service"
    build:
      context: ./payment-service
    environment:
      - "AXONSERVER_HOST:axonserver"
      - "AXONSERVER_PORT:8124"
    ports:
      - "8081:8081"
    depends_on:
      - axonserver
    networks:
      - axonnet
  shipping-service:
    container_name: "shipping-service"
    build:
      context: ./shipping-service
    environment:
      - "AXONSERVER_HOST:axonserver"
      - "AXONSERVER_PORT:8124"
    ports:
      - "8082:8082"
    depends_on:
      - axonserver
    networks:
      - axonnet
  bank-account-service:
    container_name: "bank-account-service"
    build:
      context: ./bank-account-service
    environment:
      - "AXONSERVER_HOST:axonserver"
      - "AXONSERVER_PORT:8124"
    ports:
      - "8084:8084"
    depends_on:
      - axonserver
    networks:
      - axonnet
networks:
  axonnet:
    driver: bridge
