#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
server:
  port: 8084
spring:
  application:
    name: bank-account-service
  datasource:
    platform: mysql
    url: jdbc:mysql://172.20.111.188:3306/bank
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Java12345!
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
axon:
  axonserver:
    servers: ${AXONSERVER_HOST:axonserver}:${AXONSERVER_PORT:8124}